### ISSUE TITLE
Cannot destructure property `styles` of 'undefined' or 'null'.

### ISSUE THREAD

**Issue by carstenbaumhoegger** [ionic-team/angular-toolkit#109]
Hey!

I get the following error, when I update `@ionic/angular-toolkit` from v1.4.1 to v1.5.0:

```
> ng run app:ionic-cordova-serve --host=0.0.0.0 --port=8100 --cordova-mock
[ng] Cannot destructure property `styles` of 'undefined' or 'null'.
[ng] TypeError: Cannot destructure property `styles` of 'undefined' or 'null'.
[ng]     at Object.getCommonConfig (/Users/carstenbaumhoegger/Docker/tabya/bauhofmanagement/frontend/mobile/node_modules/@angular-devkit/build-angular/src/angular-cli-files/models/webpack-configs/common.js:33:107)
[ng]     at BrowserBuilder.buildWebpackConfig (/Users/carstenbaumhoegger/Docker/tabya/bauhofmanagement/frontend/mobile/node_modules/@angular-devkit/build-angular/src/browser/index.js:81:31)
[ng]     at CordovaDevServerBuilder.buildWebpackConfig (/Users/carstenbaumhoegger/Docker/tabya/bauhofmanagement/frontend/mobile/node_modules/@angular-devkit/build-angular/src/dev-server/index.js:109:46)
[ng]     at CordovaDevServerBuilder.buildWebpackConfig (/Users/carstenbaumhoegger/Docker/tabya/bauhofmanagement/frontend/mobile/node_modules/@ionic/angular-toolkit/builders/cordova-serve/index.js:47:22)
[ng]     at MergeMapSubscriber.rxjs_1.from.pipe.operators_1.concatMap [as project] (/Users/carstenbaumhoegger/Docker/tabya/bauhofmanagement/frontend/mobile/node_modules/@angular-devkit/build-angular/src/dev-server/index.js:36:40)
[ng]     at MergeMapSubscriber._tryNext (/Users/carstenbaumhoegger/Docker/tabya/bauhofmanagement/frontend/mobile/node_modules/@angular-devkit/build-angular/node_modules/rxjs/internal/operators/mergeMap.js:69:27)
[ng]     at MergeMapSubscriber._next (/Users/carstenbaumhoegger/Docker/tabya/bauhofmanagement/frontend/mobile/node_modules/@angular-devkit/build-angular/node_modules/rxjs/internal/operators/mergeMap.js:59:18)
[ng]     at MergeMapSubscriber.Subscriber.next (/Users/carstenbaumhoegger/Docker/tabya/bauhofmanagement/frontend/mobile/node_modules/@angular-devkit/build-angular/node_modules/rxjs/internal/Subscriber.js:67:18)
[ng]     at TapSubscriber._next (/Users/carstenbaumhoegger/Docker/tabya/bauhofmanagement/frontend/mobile/node_modules/@angular-devkit/build-angular/node_modules/rxjs/internal/operators/tap.js:65:26)
[ng]     at TapSubscriber.Subscriber.next (/Users/carstenbaumhoegger/Docker/tabya/bauhofmanagement/frontend/mobile/node_modules/@angular-devkit/build-angular/node_modules/rxjs/internal/Subscriber.js:67:18)
[ng]     at MergeMapSubscriber.notifyNext (/Users/carstenbaumhoegger/Docker/tabya/bauhofmanagement/frontend/mobile/node_modules/@angular-devkit/build-angular/node_modules/rxjs/internal/operators/mergeMap.js:92:26)
[ng]     at InnerSubscriber._next (/Users/carstenbaumhoegger/Docker/tabya/bauhofmanagement/frontend/mobile/node_modules/@angular-devkit/build-angular/node_modules/rxjs/internal/InnerSubscriber.js:28:21)
[ng]     at InnerSubscriber.Subscriber.next (/Users/carstenbaumhoegger/Docker/tabya/bauhofmanagement/frontend/mobile/node_modules/@angular-devkit/build-angular/node_modules/rxjs/internal/Subscriber.js:67:18)
[ng]     at SafeSubscriber.__tryOrUnsub (/Users/carstenbaumhoegger/Docker/tabya/bauhofmanagement/frontend/mobile/node_modules/@angular/cli/node_modules/@angular-devkit/architect/node_modules/rxjs/internal/Subscriber.js:209:16)
[ng]     at SafeSubscriber.next (/Users/carstenbaumhoegger/Docker/tabya/bauhofmanagement/frontend/mobile/node_modules/@angular/cli/node_modules/@angular-devkit/architect/node_modules/rxjs/internal/Subscriber.js:147:22)
[ng]     at Subscriber._next (/Users/carstenbaumhoegger/Docker/tabya/bauhofmanagement/frontend/mobile/node_modules/@angular/cli/node_modules/@angular-devkit/architect/node_modules/rxjs/internal/Subscriber.js:90:26)

[ERROR] ng has unexpectedly closed (exit code 1).
```

Here's my ionic info:
```
Ionic:

   ionic (Ionic CLI)             : 4.12.0 (/usr/local/lib/node_modules/ionic)
   Ionic Framework               : @ionic/angular 4.1.2
   @angular-devkit/build-angular : 0.13.6
   @angular-devkit/schematics    : 7.3.6
   @angular/cli                  : 7.3.1
   @ionic/angular-toolkit        : 1.5.0

Cordova:

   cordova (Cordova CLI) : 8.1.2 (cordova-lib@8.1.1)
   Cordova Platforms     : android 7.1.4, ios 4.5.5
   Cordova Plugins       : cordova-plugin-ionic-keyboard 2.1.3, cordova-plugin-ionic-webview 4.0.0, (and 11 other plugins)

System:

   ios-deploy : 1.9.4
   NodeJS     : v10.15.0 (/usr/local/bin/node)
   npm        : 6.8.0
   OS         : macOS Mojave
   Xcode      : Xcode 10.2 Build version 10E125
```

There are no breaking changes mentioned in the Changelog, so I'm wondering what I have to change to get the update working?

**Comment by fmflame** [comment]
Same issue here. Rolled back to 1.4.1 for now.

**Comment by dotNetkow** [comment]
To add some more detail, this breaks LiveReload functionality. Example command:

ionic cordova run android -l

Rolling back also worked for me.

**Comment by dwieeb** [comment]
There is an open PR to fix this: https://github.com/ionic-team/angular-toolkit/pull/107
